[build]
  command = "pnpm build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[functions]
  node_bundler = "esbuild"

# Dynamic rendering handled by @netlify/plugin-nextjs

# Redirects for SPA routing
[[redirects]]
  from = "/onboarding/*"
  to = "/onboarding/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/index.html"
  status = 200

# API redirects (fallback for old API routes)
[[redirects]]
  from = "/api/onboarding/start"
  to = "/.netlify/functions/onboarding-start"
  status = 200

[[redirects]]
  from = "/api/onboarding/message"
  to = "/.netlify/functions/onboarding-message"
  status = 200

[[redirects]]
  from = "/api/onboarding/complete"
  to = "/.netlify/functions/onboarding-complete"
  status = 200

# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm dev"
  port = 8888
  targetPort = 3000
  framework = "#auto"
  autoLaunch = false
