# StartupAI CrewAI Task Configurations
# Evidence-Led Strategy Platform - 6 Core Tasks
# Reference: /home/chris/startupai.site/docs/technical/two-site-implementation-plan.md

evidence_collection:
  description: |
    Collect and organize evidence related to the strategic question: {strategic_question}
    
    Focus on:
    1. Identifying relevant sources (market reports, competitor analysis, customer feedback)
    2. Extracting key data points and insights
    3. Organizing evidence by theme and relevance
    4. Ensuring comprehensive coverage of the question
    
    Project context: {project_context}
    Target sources: {target_sources}
  expected_output: |
    A structured collection of evidence items including:
    - Source URLs and citations
    - Key excerpts and data points
    - Relevance scores and tags
    - Initial quality assessment
  agent: research_agent

evidence_analysis:
  description: |
    Analyze collected evidence to identify patterns, trends, and strategic insights
    for the question: {strategic_question}
    
    Focus on:
    1. Pattern recognition across evidence items
    2. Trend identification and trajectory analysis
    3. Gap analysis and missing evidence
    4. Confidence levels for each insight
    
    Previous evidence: {evidence_collection_output}
  expected_output: |
    A comprehensive analysis report including:
    - Key patterns and trends identified
    - Strategic insights and implications
    - Evidence strength assessment
    - Recommended follow-up research
  agent: analysis_agent

evidence_validation:
  description: |
    Validate the quality, credibility, and relevance of collected evidence
    for: {strategic_question}
    
    Focus on:
    1. Source credibility assessment
    2. Bias detection and correction
    3. Cross-reference verification
    4. Relevance scoring
    
    Evidence to validate: {evidence_collection_output}
  expected_output: |
    A validation report including:
    - Quality scores for each evidence item
    - Credibility assessment of sources
    - Identified biases or concerns
    - Recommendations for evidence improvement
  agent: validation_agent

insight_synthesis:
  description: |
    Synthesize analysis and validation results into coherent strategic insights
    for: {strategic_question}
    
    Focus on:
    1. Combining insights from multiple sources
    2. Building evidence-based arguments
    3. Addressing counter-evidence
    4. Formulating actionable recommendations
    
    Analysis results: {evidence_analysis_output}
    Validation results: {evidence_validation_output}
  expected_output: |
    A synthesis document including:
    - Key strategic insights with evidence links
    - Confidence levels and supporting evidence
    - Alternative perspectives considered
    - Recommended strategic actions
  agent: synthesis_agent

report_generation:
  description: |
    Generate a professional strategic report for: {strategic_question}
    
    Focus on:
    1. Clear executive summary
    2. Evidence-based findings presentation
    3. Visual representation of insights
    4. Actionable recommendations with priorities
    
    Synthesis results: {insight_synthesis_output}
    Report format: {report_format}
  expected_output: |
    A professional strategic report including:
    - Executive summary (1-2 pages)
    - Detailed findings with evidence citations
    - Strategic recommendations with priorities
    - Supporting data visualizations
    - Appendix with full evidence inventory
  agent: reporting_agent

workflow_orchestration:
  description: |
    Orchestrate the entire strategic analysis workflow for: {strategic_question}
    
    Focus on:
    1. Task sequencing and dependency management
    2. Agent coordination and communication
    3. Quality control checkpoints
    4. Timeline management and progress tracking
    
    Project deadline: {project_deadline}
    Priority level: {priority_level}
  expected_output: |
    A workflow execution report including:
    - Task completion status
    - Agent performance metrics
    - Timeline adherence
    - Quality gate results
    - Final deliverable status
  agent: orchestration_agent
