# ============================================================================
# DEFAULT BUILD CONFIGURATION (Production)
# ============================================================================
[build]
  command = "cd frontend && pnpm build"
  publish = "frontend/.next"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "9.12.1"
  # Allow server-side environment variables in Next.js API routes
  # These are only accessed at runtime, not embedded in client code
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_SERVICE_ROLE_KEY,DATABASE_URL,SUPABASE_URL"

# ============================================================================
# STAGING CONTEXT (staging branch - Deployed Environment)
# ============================================================================
# Branch deploy from 'staging' git branch
# URL: https://staging--app-startupai-site.netlify.app
[context.staging]
  command = "cd frontend && pnpm build"

[context.staging.environment]
  NODE_ENV = "staging"
  NEXT_PUBLIC_MARKETING_URL = "https://staging--startupai-site.netlify.app"
  NEXT_PUBLIC_APP_URL = "https://staging--app-startupai-site.netlify.app"
  NEXT_PUBLIC_SITE_URL = "https://staging--app-startupai-site.netlify.app"

# ============================================================================
# DEV CONTEXT (local netlify dev only - for testing Functions)
# ============================================================================
# This context is for local 'netlify dev' command
# Used for testing Netlify Functions locally
[context.dev.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_MARKETING_URL = "http://localhost:8888"
  NEXT_PUBLIC_APP_URL = "http://localhost:8889"
  NEXT_PUBLIC_SITE_URL = "http://localhost:8889"

# ============================================================================
# PRODUCTION CONTEXT (main branch)
# ============================================================================
[context.production]
  command = "cd frontend && pnpm build"
  
[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_MARKETING_URL = "https://startupai-site.netlify.app"
  NEXT_PUBLIC_APP_URL = "https://app-startupai-site.netlify.app"
  NEXT_PUBLIC_SITE_URL = "https://app-startupai-site.netlify.app"

# ============================================================================
# BRANCH DEPLOY PREVIEWS
# ============================================================================
[context.branch-deploy]
  command = "cd frontend && pnpm build"

[context.branch-deploy.environment]
  NODE_ENV = "staging"

# ============================================================================
# NETLIFY DEV LOCAL SERVER
# ============================================================================
[dev]
  command = "cd frontend && npx next dev --turbopack"
  port = 8889
  targetPort = 3000
  autoLaunch = false
  framework = "#custom"

# Enable Next.js on Netlify
[[plugins]]
  # Pin to 5.14.4 for Next.js 15 compatibility (fixes missing start-server module)
  package = "@netlify/plugin-nextjs"
  pinned_version = "5.14.4"

[functions]
  directory = "netlify/functions"
  # Python functions will use Python 3.10 automatically

[[redirects]]
  from = "/api/analyze-background"
  to = "/.netlify/functions/crew-analyze-background"
  status = 200

# Note: Removed catch-all redirect - Next.js plugin handles routing

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
