/**
 * Landing Page Variants Schema
 *
 * Stores A/B test landing page variants generated by CrewAI.
 * Each variant is stored in Supabase Storage with metadata tracked here.
 *
 * @story US-AD01
 */

import { pgTable, text, timestamp, uuid, jsonb } from 'drizzle-orm/pg-core';

export const landingPageVariants = pgTable('landing_page_variants', {
  id: uuid('id').defaultRandom().primaryKey().notNull(),

  // Run identification
  runId: text('run_id').notNull(),
  variantName: text('variant_name').notNull(),

  // Storage location
  storagePath: text('storage_path').notNull(),
  publicUrl: text('public_url').notNull(),

  // Content hash for deduplication
  htmlHash: text('html_hash'),

  // Timestamps
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  expiresAt: timestamp('expires_at', { withTimezone: true }),

  // Additional metadata
  metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}),
});

export type LandingPageVariant = typeof landingPageVariants.$inferSelect;
export type NewLandingPageVariant = typeof landingPageVariants.$inferInsert;
