openapi: 3.0.3
info:
  title: Gateway API
  version: 1.0.0
  description: Public intake and status endpoints for the consulting platform.
servers:
  - url: https://api.example.com
paths:
  /intake:
    post:
      summary: Create intake job
      operationId: createIntake
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntakeRequest'
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptedResponse'
  /status/{id}:
    get:
      summary: Get job status
      operationId: getStatus
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    IntakeRequest:
      type: object
      required: [brief, objectives]
      properties:
        brief:
          type: string
        objectives:
          type: array
          items:
            type: string
        pii_level:
          type: string
          enum: [none, low, moderate, high]
        budget_tier:
          type: string
          enum: [standard, premium]
    AcceptedResponse:
      type: object
      required: [id, status]
      properties:
        id:
          type: string
        status:
          type: string
          enum: [accepted]
        status_url:
          type: string
          format: uri
    StatusResponse:
      type: object
      required: [id, state]
      properties:
        id:
          type: string
        state:
          type: string
          enum: [queued, running, completed, failed]
        artifacts:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              url:
                type: string
                format: uri
