name: Deploy Multi-Agent Platform

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/multi-agent-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/multi-agent-frontend:latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy strategyzer-ai-backend \
            --source ./backend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 4000 \
            --memory 2Gi \
            --cpu 2 \
            --timeout 300 \
            --set-env-vars MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            --set-env-vars OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            --set-env-vars JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --set-env-vars MASTER_ENCRYPTION_KEY="${{ secrets.MASTER_ENCRYPTION_KEY }}" \
            --set-env-vars NODE_ENV=production \
            --project andrewcave

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy strategyzer-ai-frontend \
            --source ./frontend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 3000 \
            --memory 1Gi \
            --cpu 1 \
            --timeout 300 \
            --set-env-vars NEXT_PUBLIC_API_URL="https://strategyzer-ai-backend-e42x4wjxiq-uc.a.run.app/api" \
            --project andrewcave
