name: Deploy Multi-Agent Platform

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up GCloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: us-central1-docker.pkg.dev/andrewcave/strategyzer-ai/strategyzer-ai-backend:latest

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: us-central1-docker.pkg.dev/andrewcave/strategyzer-ai/strategyzer-ai-frontend:latest

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy strategyzer-ai-backend \
            --image us-central1-docker.pkg.dev/andrewcave/strategyzer-ai/strategyzer-ai-backend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 4000 \
            --memory 2Gi \
            --cpu 2 \
            --timeout 300 \
            --set-secrets=MONGODB_URI=MONGODB_URI:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,JWT_SECRET=JWT_SECRET:latest,MASTER_ENCRYPTION_KEY=MASTER_ENCRYPTION_KEY:latest \
            --set-env-vars NODE_ENV=production \
            --project andrewcave

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy strategyzer-ai-frontend \
            --image us-central1-docker.pkg.dev/andrewcave/strategyzer-ai/strategyzer-ai-frontend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 3000 \
            --memory 1Gi \
            --cpu 1 \
            --timeout 300 \
            --set-env-vars NEXT_PUBLIC_API_URL="https://strategyzer-ai-backend-e42x4wjxiq-uc.a.run.app/api" \
            --project andrewcave
